export const ROLES_PROVIDER = 'ROLES_PROVIDER';
export const STATES_MOVIES_PROVIDER = 'STATES_MOVIES_PROVIDER';

export const JWT_SECRET = 'JWT_SECRET';
export const EMAIL_TRANSPORT = 'EMAIL_TRANSPORT';
export const MINUTES_EXPIRES_TOKEN_JWT = 9000;
export const MINUTES_EXPIRES_TOKEN_RECOVERY_PASSWORD = 10;

export const BUY_OPERATION = 'buy';
export const RENT_OPERATION = 'rent';
export const RETURN_OPERATION = 'returned';

export const ENV_CONSTS = {
  JWT_SECRET,
  EMAIL_TRANSPORT,
};
